### PR TITLE
#42

### LINKED ISSUE #42: Show loading members instead of collectors in community page

### PR DESCRIPTION
**Pull request by jayantdahiya**
## What does this PR do?

Changed loader text from "Loading Collectors" to "Loading Members".

Fixes #42 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

- [ ] Test A
- [ ] Test B

### CODE REVIEW

**Comment by bigint** [comment]
@jayantdahiya We need to show `members` only in the community page, but still we want to show them as `collectors` in the collect modal 🙇🏼 

Also give the valid name to PR and commits 🙏🏼

**Comment by jayantdahiya** [comment]
Okay got it I'll make sure of this in future ✌️

**Comment by jayantdahiya** [comment]
Yes I'm on it 🧑‍💻

**Comment by shanpriyan** [comment]
> Okay got it I'll make sure of this in future ✌️

@jayantdahiya You can still edit your PR, please change the PR title to a meaningful and relevant name. 🚀

**Comment by jayantdahiya** [comment]
> @jayantdahiya We need to show `members` only in the community page, but still we want to show them as `collectors` in the collect modal 🙇🏼
> 
> Also give the valid name to PR and commits 🙏🏼

@bigint, can you give me more info on the collect modal please?

**Pull request merged**
