### PR TITLE
fix: change bolt icon to bell icon for notification in navbar

### LINKED ISSUE #2172: Change bolt icon to bell icon for notification in navbar

### PR DESCRIPTION
**Pull request by foolo**
## What does this PR do?

Fixes #2172

New look:
newicon

Note: I think the bell icon in Heroicons V2 looks a bit better:
bell_v2

But then we would need to switch to V2, which would change all other icons too, so it may not be desired right now.

## Type of change

- [x] Enhancement (non-breaking small changes to existing functionality)

### CODE REVIEW

**Comment by bigint** [comment]
@foolo I tried v2 but all the fonts are very light, we will be forking heroicons to our own and modify it heavily

**Comment by bigint** [comment]
Screenshot 2023-03-24 at 10 22 53 PM

@foolo we missed on mobile view 🙈

**Comment by foolo** [comment]
> Screenshot 2023-03-24 at 10 22 53 PM
> 
> @foolo we missed on mobile view see_no_evil

Ahh :) Now I see that there are more LightningBoltIcon in the project. I'll look at the others as well.

**Comment by foolo** [comment]
Changed it in some more places:

Screenshot_2023-03-24_18-10-28

**Review by bigint — APPROVED** [review]
**LGTM** :shipit: 

Rad LGTM

**Pull request merged**
