### PR TITLE
feat: add button

### PR DESCRIPTION
**Pull request by harish-sethuraman**
### <samp>🤖 Generated by Copilot at 5448f84</samp>

This pull request improves the accessibility, usability, and consistency of various buttons in the web app. It renames the `icon` prop of the `Button` component to `leadingIcon`, changes the icons and labels of some report buttons, adds aria-labels, tooltips, and disabled states to many buttons, and changes the text and color of some delete buttons. It affects multiple files in the `apps/web/src/components` directory.

## Related issues

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### <samp>🤖 Generated by Copilot at 5448f84</samp>

*  Rename `icon` prop to `leadingIcon` for `Button` components to avoid confusion with `trailingIcon` prop ([link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-167e43ca14e31af121fc91851e280702f844b51a386e0dd70764c1e8651bdc1bL132-R132), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-167e43ca14e31af121fc91851e280702f844b51a386e0dd70764c1e8651bdc1bL144-R144), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-175403612af948ab5a9aed1b111d24448b156cc856927d47f556e01221a56517L556-R556), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-0b17ae730645cca1e329c62e6d6f97347015e8ac56c189552e484a198785bcf6L52-R52), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-10fa70e6053fe1d84241598d9bbea0e3b28cf7103f61edc7ba00f445db1ecdf1L101-R101), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-051c5aa8ed716f2a43344cf26ef7f981c4ad1884f3cf442ae394da8e5527aa04L128-R128), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-96b48682c7a55b1eb2ee43af7185f3120af33a0c5794c6821b416682c44754b4L13-R13), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-1aecb32f75f212fc7245e138320f8bc740da24825d37a50a417be37016b95f64L254-R254), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-7977996b7f0dbc1f616a63dabbfd3cf4d7e894542863a65c8f492813fadecaebL434-R434), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-7a5caf1e15c1ed5997ca02f9327b303f68964f33a31287e81c54eacb72714113L75-R75), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-7a5caf1e15c1ed5997ca02f9327b303f68964f33a31287e81c54eacb72714113L123-R123), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-7a5caf1e15c1ed5997ca02f9327b303f68964f33a31287e81c54eacb72714113L134-R134), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-4140e9fa5dba053d642a89f16e93d79a9b944b23e11e6f1746e3411ad9b0542aL168-R168), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-431256eec597b5a6fbe8bc86f1e0997372664195fb9bbbe33a35c56758b2a249L206-R206), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-431256eec597b5a6fbe8bc86f1e0997372664195fb9bbbe33a35c56758b2a249L214-R214), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-cfc16ec8965a8ee0f8d417864ef8445f94b2dea6959342a0f0db76ab033f0408L76-R76), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-cfc16ec8965a8ee0f8d417864ef8445f94b2dea6959342a0f0db76ab033f0408L89-R92), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-cfc16ec8965a8ee0f8d417864ef8445f94b2dea6959342a0f0db76ab033f0408L111-R114), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-24350b827973549fb283ddcf1c5a7ee4401f88d7a72d2205a78a1a0350c80cd6L130-R132), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-24350b827973549fb283ddcf1c5a7ee4401f88d7a72d2205a78a1a0350c80cd6L155-R157), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-1fa1065ebf72ab9da791b7a0cdc742f6baffa25342dfeb1f99dfefd1c9350fdfL117-R117), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-fdab972f0563d8bedc5367cd67214a8d3abb16597730dc51f9dba258298c2a11L77-R77), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-fdab972f0563d8bedc5367cd67214a8d3abb16597730dc51f9dba258298c2a11L99-R99), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-cf0a97986c4205646f837237d73d253f968c2212d1745a1bf33b795784a7db1cL204-R204), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-e1d95068b7cec5b12e33c5d65d074c4ba6fc0717fb0c6239c17821998ff45526L211-R211), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-cc605dc6510d575486ca4cc4d51a003ca10dfeb338fced8f413d3c60d1543c90L282-R282), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-2e5f548614ad2d3ac2c9a19db89a67ae351e1b12b689ba5857fad457f54d773bL108-R108), [link](https://github.com/lensterxyz/lenster/pull/2538/files?diff=unified&w=0#diff-13d4bceb37aa9a8fbfb289da32670451dffff4b1aa212cc07a4559e5bef0c3f2L171-R171))

## Emoji

🎨🔄♿

### CODE REVIEW

**Comment by bigint** [comment]
Screenshot 2023-04-16 at 12 57 12 PM

Follow button looks weird 🙇🏼

**Comment by bigint** [comment]
Screenshot 2023-04-16 at 12 58 04 PM

Disabled state not working

**Comment by bigint** [comment]
Screenshot 2023-04-16 at 12 58 37 PM

outline hover is solid, but expected is something like this

Screenshot 2023-04-16 at 12 59 04 PM

**Comment by bigint** [comment]
Can we also reduce the size of small button a little bit, cuz seeing lot of whitespace 🙇🏼

**Comment by saagu335** [comment]
Seeing bit more whitespace 🙈, we can discuss this @bigint 💬

**Comment by bigint** [comment]
Howdu, nange same feel aguthathe @saagu335 👍🏼

I'll talk internally with some designers

**Comment by harish-sethuraman** [comment]
👀 Yea lets settle up on one thing either primer.style kinda one or other one. now we are almost at middle of both. Also @saagu335 which white space are you talking about? text and border one?

**Comment by saagu335** [comment]
@harish-sethuraman Yea we can follow Untitled UI for design and Primer for button sizes and typography

GitHub Primer Figma: https://www.figma.com/file/sSRSzn10S2RNvocuhpyw4C/Primer-Web-(Community)?node-id=16163-61220&t=lL3tTgBKE3Mg2lG9-0

**Pull request closed without merging**
