### PR TITLE
fix: JS-0746 rule - prefer to accompany onClick with some elements

### LINKED ISSUE #114: (JS-0746) Prefer to accompany `onClick` with some elements
## Description
Enforce `onClick` is accompanied by at least one of the following: `onKeyUp`, `onKeyDown`, `onKeyPress`. Coding for the keyboard is important for users with physical disabilities who cannot use a mouse, AT compatibility, and screenreader users. This does not apply for interactive or hidden elements

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/lensterxyz/lenster/issue/JS-0746/occurrences/](https://deepsource.io/gh/lensterxyz/lenster/issue/JS-0746/occurrences/)

### PR DESCRIPTION
**Pull request by piraces**
## What does this PR do?

Fixes #114

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

n/a. Non breaking changes. Only accompany `onClick` handling with `onKeyDown` for accesibility reasons.

### CODE REVIEW

**Comment by piraces** [comment]
Working on introduced issues in deepsource...

**Comment by piraces** [comment]
Done! 😄

**Comment by bigint** [comment]
We have migrated to monorepo, can you please sync with `main` branch 🙏🏼

**Comment by piraces** [comment]
Done @bigint ! I have solved other "introduced" results that deepsource identified, resulting in a total of 135 resolved.

(P.S: the monorepo change its great! I have never tried turborepo and its very fast 👍 )

**Comment by bigint** [comment]
This is not a high priority issue 🙇🏼 

Closing this for now 🙏🏼

**Pull request closed without merging**
