### PR TITLE
Timeline thread - show 3 items with OG post

### LINKED ISSUE #956: Timeline v2 - Thread with OP post
The middle comment in thread is missing now in timeline v2.

image

### PR DESCRIPTION
**Pull request by sasicodes**
## What does this PR do?

Fixes #956 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sasicodes** [comment]
There still exists a issue in response.

image

**Comment by bigint** [comment]
@sasicodes any updates on this?

**Comment by sasicodes** [comment]
hold because of an api issue. josh might check soon.

**Comment by bigint** [comment]
We have migrated to monorepo, can you please sync with `main` branch 🙏🏼

**Pull request closed without merging**
