### PR TITLE
feat: add search icon in search bar

### LINKED ISSUE #68: Add search icon in mobile navbar

### PR DESCRIPTION
**Pull request by shanpriyan**
CodeSandbox logoCodeSandbox logo&nbsp; Open in CodeSandbox <a href="https://codesandbox.io/p/github/shanpriyan/lenster/feat/search-icon?workspace=%7B%22gitSidebarPanel%22:%22PR%22,%22sidebarPanel%22:%22GIT%22%7D">Web Editor</a> | <a href="https://codesandbox.io/p/vscode?owner=shanpriyan&repo=lenster&branch=feat/search-icon">VS Code</a>

- Added search icon in search bar.
- If type `"search"` is passed to `Input` component, it will render a search icon.

**Before**
image
image

**After**
image
image

Resolves #68

### CODE REVIEW

**Comment by bigint** [comment]
@shanpriyan now the input looks too huge 😕 

image

Screenshot 2022-07-29 at 1 23 40 PM

**Comment by danschewy** [comment]
I quite like your approach, I did it a little differently, probably overkill
https://github.com/lensterxyz/lenster/pull/173

**Comment by shanpriyan** [comment]
> @shanpriyan now the input looks too huge 😕
> 
> image
> 
> Screenshot 2022-07-29 at 1 23 40 PM

@bigint matched Searchbar with the current one

**Comment by bigint** [comment]
@shanpriyan closing this in favour of #173 🙏🏼 

That PR looks simple without any state and events 🙇🏼

**Pull request closed without merging**
