### PR TITLE
feat: add optimistic message sending

### LINKED ISSUE #2944: Optimistically send messages
### Summary

Right now when sending attachments thru messages, it takes a while to send which blocks the UI. It would be great if we can add optimistic sending and then handle the error case if it fails (maybe adding an error icon that says failed to send when hovering?).

Use case:
- Send an attachment and immediately unblock input/send button UI to allow sending another message
- Cached attachment should show in the messages list while sending
- If the attachment succeeds to send, do nothing.
- If the attachment fails to send, indicate the failure in the message list.
- Allow multiple in-progress messages by sending an attachment and then immediately sending another

### PR DESCRIPTION
**Pull request by rygine**
## What does this PR do?

In addition to optimistic message sending, this PR also incorporates some bug fixes that I noticed during development.

#### Streaming code updates

Streaming related code has been updated to match the code in the [XMTP React SDK](https://github.com/xmtp/xmtp-web/tree/main/packages/react-sdk) in order to make the streams behave more consistently.

#### Messages scroll position

I noticed that when a conversation is selected, the latest message isn't always displayed because the messages container isn't scrolled to the bottom. Now when selecting a conversation, the messages list is automatically scrolled to the bottom.

### Pending issues

When sending images, there's a brief period when the message transitions from the "pending" to "sent" state. During this time, the rendered message switches from the new `AttachmentPreviewInline` component to the `RemoteAttachmentPreview` component. The initial state of the `RemoteAttachmentPreview` component is `UNLOADED`, which displays a view link while the image is loaded from the cache or URL. This can create some jumpiness in the messages list if a user sends multiple messages while an image is uploaded. See preview video below.

Is this something we want to address?

### Preview

https://github.com/lensterxyz/lenster/assets/2925672/3f69abad-8fe6-4045-a84e-d42e899131bf

### <samp>🤖 Generated by Copilot at 09a288d</samp>

This pull request adds the feature of sending attachments with messages and implements optimistic message sending and real-time updates of messages and conversations. It introduces new types, components, and hooks to handle different message content and status, and to stream data from the server. It also refactors some existing hooks and components to improve performance and readability. It affects the files `apps/web/src/components/Messages/*`, `apps/web/src/components/utils/hooks/*`, and `apps/web/src/store/message.ts`.

## Related issues

Resolves #2944 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### <samp>🤖 Generated by Copilot at 09a288d</samp>

*  Modify the `Composer` component to allow sending attachments and text messages in one call, and to display the attachment preview inline ([link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d81c35a93562e83d4694a0ecd6a92790bcd4738149dd0c14b0613fa889124737L1-R10), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d81c35a93562e83d4694a0ecd6a92790bcd4738149dd0c14b0613fa889124737L34-R42), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d81c35a93562e83d4694a0ecd6a92790bcd4738149dd0c14b0613fa889124737R74-R88), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d81c35a93562e83d4694a0ecd6a92790bcd4738149dd0c14b0613fa889124737L92-R122), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d81c35a93562e83d4694a0ecd6a92790bcd4738149dd0c14b0613fa889124737L101-R190), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d81c35a93562e83d4694a0ecd6a92790bcd4738149dd0c14b0613fa889124737L148-R200), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d81c35a93562e83d4694a0ecd6a92790bcd4738149dd0c14b0613fa889124737L205-R255), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d81c35a93562e83d4694a0ecd6a92790bcd4738149dd0c14b0613fa889124737L255-R294))
*  Modify the `Message` component to use the `useSendOptimisticMessage` hook and the `queuedMessages` state for sending messages optimistically and displaying the message status and actions ([link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-2ce189b37041c30ccd1e2909ceecbb30ea9b59738f19f0311bf70e40993bca6bL6-R10), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-2ce189b37041c30ccd1e2909ceecbb30ea9b59738f19f0311bf70e40993bca6bL18-R22), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-2ce189b37041c30ccd1e2909ceecbb30ea9b59738f19f0311bf70e40993bca6bL36-R120), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-2ce189b37041c30ccd1e2909ceecbb30ea9b59738f19f0311bf70e40993bca6bL96-R169))
*  Modify the `MessageContent` component to render a custom preview for the queued messages, such as an attachment preview ([link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-e18bb861a0d2f49b293cd153df332103b6d3186f7f7c1d6eba1b578d2b2e9074R2-R6), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-e18bb861a0d2f49b293cd153df332103b6d3186f7f7c1d6eba1b578d2b2e9074L10-R15), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-e18bb861a0d2f49b293cd153df332103b6d3186f7f7c1d6eba1b578d2b2e9074R29-R33))
*  Modify the `MessageTile` component to display an icon and a text to indicate the status of the message, such as pending, failed, or sent, and to allow the user to retry or cancel a failed message ([link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096L1-R7), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096L13-R19), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096L27-R33), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096R46-R88), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096L79-R132))
*  Modify the `MessagesList` component to scroll to the bottom of the message list when a conversation is selected ([link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096L144-R194), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096R211), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096R223-R227), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-d6e3ea08187ae6cc461d790284163296d5e73c9bb6ecf27bea3ef858dcc2f096L182-R242))
*  Modify the `useGetMessages` hook to simplify the hook interface and to use the existing conversations state instead of passing a conversation object ([link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-f084f244ab61e36f940d814ccee7c08f0df68e0837830889b1a6ba9f613d97f0L2-R7), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-f084f244ab61e36f940d814ccee7c08f0df68e0837830889b1a6ba9f613d97f0R15), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-f084f244ab61e36f940d814ccee7c08f0df68e0837830889b1a6ba9f613d97f0L45-R42))
*  Modify the `useMessagePreviews` hook to use the `useStreamAllMessages` and `useStreamConversations` hooks for streaming new messages and conversations in real-time, and to memoize the `getProfileFromKey` function ([link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-b4f3b185340d536623bfcecce43624e3f8d2155a371a469dacb7aaf372397bf3L11-R14), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-b4f3b185340d536623bfcecce43624e3f8d2155a371a469dacb7aaf372397bf3R20-R21), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-b4f3b185340d536623bfcecce43624e3f8d2155a371a469dacb7aaf372397bf3L65-R78), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-b4f3b185340d536623bfcecce43624e3f8d2155a371a469dacb7aaf372397bf3L183-R188), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-b4f3b185340d536623bfcecce43624e3f8d2155a371a469dacb7aaf372397bf3L234-R273))
*  Modify the `message` store to define and implement the message queue state and the actions to update it ([link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-bf53ea74161761cc199afb3af1d4962130ed9eb89d191b26bd5fb551e83d534dR1-R4), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-bf53ea74161761cc199afb3af1d4962130ed9eb89d191b26bd5fb551e83d534dR20-R30), [link](https://github.com/lensterxyz/lenster/pull/3021/files?diff=unified&w=0#diff-bf53ea74161761cc199afb3af1d4962130ed9eb89d191b26bd5fb551e83d534dR65-R111))

## Emoji

🚀📎🛠️

### CODE REVIEW

**Comment by bigint** [comment]
https://github.com/lensterxyz/lenster/assets/69431456/baf67ff3-064e-4ef4-8686-a7bbcb8d479f

Seems like its cleaning the input after the optimistic message got set

**Comment by bigint** [comment]
I'm not sure, i'm got tons of signing prompt in the wallet

**Comment by rygine** [comment]
> Seems like its cleaning the input after the optimistic message got set

i'm not sure i understand this. the input is cleared immediately after sending to enable sending another message quickly. am i missing something?

**Comment by rygine** [comment]
@bigint the [latest commit](https://github.com/lensterxyz/lenster/pull/3021/commits/1f2f2aca5d4f6013d4f69f67ccb4d4aae3adb6c3) fixes the multiple signature bug.

**Comment by bigint** [comment]
> i'm not sure i understand this. the input is cleared immediately after sending to enable sending another message quickly. am i missing something?


@rygine I mean, when user sends a message it got pushed to the optimistic queue and message gets processed, consider the user sending message before it get processed the user filled the inbox, once the old message got processed the input field user filled got nuked.

**Comment by bigint** [comment]
Can we also make the checkmark little bit small 🙇🏼

**Comment by bigint** [comment]
I think we don't want check mark on left side

image

**Comment by rygine** [comment]
> I mean, when user sends a message it got pushed to the optimistic queue and message gets processed, consider the user sending message before it get processed the user filled the inbox, once the old message got processed the input field user filled got nuked.

this has been fix in [this commit](https://github.com/lensterxyz/lenster/pull/3021/commits/b89351774310fa5c67d9a362150911d55d284338)

> I think we don't want check mark on left side

> Can we also make the checkmark little bit small 🙇🏼

both of these have been address in [this commit](https://github.com/lensterxyz/lenster/pull/3021/commits/4f380724fd7c3c683d95ab4e92f15fac9fd19ed4)

**preview**

status_icons

**Comment by bigint** [comment]
> I think we don't want check mark on left side

@rygine I mean we don't want the check mark in sender side I guess 🙇🏼

**Comment by bigint** [comment]
But merging now, i can remove it 🙇🏼

**Pull request merged**
