### PR TITLE
feat: keep track of partially composed messages

### LINKED ISSUE #1007: Keep track of partially composed messages
### Summary

Unsent messages get cleared when you navigate to a different conversation, following https://github.com/lensterxyz/lenster/pull/1005.

We should probably keep track of the state of all unsent messages so that when the user navigates back to a conversation they can resume their writing.

### PR DESCRIPTION
**Pull request by foolo**
## What does this PR do?

Fixes #1007
Screen recording: https://user-images.githubusercontent.com/667227/212549701-e724b33e-e40b-4ffb-a59b-27b5d708d7e0.mp4

Note: Using the same localstorage key for all messages. It would also be possble to store each message as a separate key. Then no JSON parsing would be needed, and no need to read and write all messages to update just one message. But I think that there will probably not be too many messages on the same time, so I went with just one localstorage key.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How should this be tested?

Type a message in one conversation, without sending the message. Navigate to another conversation and then back to the first one. Observe that the message is restored.

### CODE REVIEW

**Comment by bigint** [comment]
Do you think using zustand for this will be better?

**Comment by bigint** [comment]
Close T-3672

**Comment by bigint** [comment]
@foolo Do you think using zustand for this will be better?

**Comment by foolo** [comment]
> @foolo Do you think using zustand for this will be better?

It might be, I'll try it!

**Comment by bigint** [comment]
@foolo is it good to review now?

**Comment by foolo** [comment]
@bigint I switched to zustand, and used the existing useMessagePersistStore store, which felt like a natural place.
But just tell if I should instead use a separate store.

**Comment by foolo** [comment]
> @foolo is it good to review now?

@bigint Yes! Unless you see any problem with using useMessagePersistStore, see previous comment https://github.com/lensterxyz/lenster/pull/1622#issuecomment-1383933635

**Comment by bigint** [comment]
**LGTM** :shipit: 

Rad LGTM

**Pull request merged**
