### PR TITLE
Feature: User Profile - don't display LensProtocol follow NFTs

### PR DESCRIPTION
**Pull request by svitekpavel**
## What does this PR do?

When you look at some user's NFTs tab, you will see a lot of "follow NFTs" from Lens protocol. I added logic to filter them out. It's not very useful to see follow NFTs as you can just go to "Following" popup.

Consideration: I looked also at GraphQL query to filter them out, but I wasn't sure how to update the GraphQL query properly. That would be my preferred solution.
- This is not possible now, confirmed with Aave team

## Type of change

- [x] Enhancement (non-breaking small changes to existing functionality)

## How should this be tested?

- Test A: Look at https://lenster.xyz/u/stani.lens - NFTs tab
- Test B: Look at his profile on this branch

## Checklist

 ✅ 

## Screenshot of problem

Screenshot 2022-11-15 at 15 28 00

### CODE REVIEW

**Comment by svitekpavel** [comment]
I asked in the Discord if we can filter out the NFTs in GraphQL query, but it's not possible yet.

Screenshot 2022-11-16 at 10 59 32

**Comment by bigint** [comment]
We have migrated to monorepo, can you please sync with `main` branch 🙏🏼

**Comment by svitekpavel** [comment]
> We have migrated to monorepo, can you please sync with `main` branch 🙏🏼

It's synced.

**Comment by bigint** [comment]
This will have problems with pagination, I think API will fix this

Closing this for now 🙇🏼

**Pull request closed without merging**
