### PR TITLE
feat: add virtualization 

### PR DESCRIPTION
**Pull request by ManyRios**
### <samp>🤖 Generated by Copilot at 0b35884</samp>

This pull request adds infinite scrolling and dynamic sizing features to various components of the web app using `react-window` and related libraries. This improves the performance and user experience of the app when dealing with large data sets of publications, transactions, notifications, and profiles. The changes affect the files `apps/web/package.json`, `apps/web/src/components/Explore/Feed.tsx`, `apps/web/src/components/Home/Highlights.tsx`, `apps/web/src/components/Home/Timeline/index.tsx`, `apps/web/src/components/Notification/List.tsx`, and `apps/web/src/components/Search/Profiles.tsx`.

## Related issues

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### <samp>🤖 Generated by Copilot at 0b35884</samp>

*  Add three new dependencies and their type definitions for rendering large lists efficiently and with infinite scrolling ([link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-14b60f636e1a2b0061da57aaf231cb1ed15a5dc0c592425ed82e58fec95d42d8R63-R65), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-14b60f636e1a2b0061da57aaf231cb1ed15a5dc0c592425ed82e58fec95d42d8R87-R89))
*  Refactor `Feed`, `Highlights`, `Timeline`, `List`, and `Profiles` components to use `AutoSizer`, `InfiniteLoader`, and `List` from the new dependencies instead of the original rendering logic ([link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-91b8a03cf0576eccd727dc531886c16eab0b27440da8250ffc770694666a9790R10-R12), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-91b8a03cf0576eccd727dc531886c16eab0b27440da8250ffc770694666a9790L66-R114), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-f1d914bec117253e3b7c15315d31e486b91c54ca9a76032225ac70eb924e16d0R11-R13), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-f1d914bec117253e3b7c15315d31e486b91c54ca9a76032225ac70eb924e16d0L59-R117), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-77c1f224dc344d814158048dcfa273b2cd34abbffe4ff264bcd4e420e340d0d5R11-R13), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-77c1f224dc344d814158048dcfa273b2cd34abbffe4ff264bcd4e420e340d0d5L79-R136), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-290d37d998503d7354bd993bbc2810218395414c7eeda5efbb2e0f438c9f5184R16-R18), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-290d37d998503d7354bd993bbc2810218395414c7eeda5efbb2e0f438c9f5184L103-R174), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-c4ea4975bcd67b55f4d25403b20e55989f4ca8b584595318ce901664fc2b8a0cR10-R12), [link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-c4ea4975bcd67b55f4d25403b20e55989f4ca8b584595318ce901664fc2b8a0cL72-R119))
*  Rename `List` from `react-window` to `Notificator` in `List.tsx` to avoid confusion with `List` from `@material-ui/core` ([link](https://github.com/lensterxyz/lenster/pull/2398/files?diff=unified&w=0#diff-290d37d998503d7354bd993bbc2810218395414c7eeda5efbb2e0f438c9f5184R16-R18))

## Emoji

🚀🔎📚

### CODE REVIEW

**Comment by bigint** [comment]
https://user-images.githubusercontent.com/69431456/230705157-e701b591-584f-445e-b9f4-6dfc3b4e2058.mov

Pagination not working 📜

**Comment by ManyRios** [comment]
> Pagination not working 📜

I just saw this a few minutes ago... fixing

**Comment by bigint** [comment]
https://user-images.githubusercontent.com/69431456/231083366-bc4c6d25-8442-406e-87ca-bea69255db36.mov

@ManyRios it's not working 🙇🏼

**Comment by saagu335** [comment]
@ManyRios any updates? can we move forward?

**Comment by ManyRios** [comment]
> @ManyRios any updates? can we move forward?

I'm checking to fix right now....

**Comment by DynaLoot11** [comment]
[Uploading lenster-main2.zip…]()

**Comment by ManyRios** [comment]
No! 🤦

**Comment by saagu335** [comment]
@ManyRios We added react-virtuosa library in https://github.com/lensterxyz/lenster/pull/2700

I think we can reuse the same for virtualization 🙏

**Pull request closed without merging**
