### PR TITLE
fix: can't read the text or contents when we are in dark mode #1253

### LINKED ISSUE #1253: Cant read the text or contents when we are in dark mode
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Its not a bug more of a UI issue

using black text on a darker screen layout doesnot seem to work please re-optimize the darkmode in Lenster.
Also please provide the light/dark mode directly on the top bar in the all pages that we can access.

Thanks.
dudewith.lens

### Expected Behavior

to be clearly identify the text when in dark mode.

### Steps To Reproduce

_No response_

### What platform(s) does this occur on?

Web, Mobile

### What browser(s) does this occur on?

Chrome, Brave

### Anything else?

image
red highlighted area = black text & background conflicting.
green highlighted area = toggle for light/dark mode.

### PR DESCRIPTION
**Pull request by chiragbadhe**
## What does this PR do?

Fixes #1253  (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [.] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

- [ ] Test A
- [ ] Test B

## Checklist

- I haven't read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bigint** [comment]
I think by default it will switch to text-black and text-white automatically 🤔

**Comment by bigint** [comment]
@chiragbadhe 🙇🏼

**Comment by chiragbadhe** [comment]
> @chiragbadhe 🙇🏼

Yes but in some browsers, it is not working well 

For more explanation:-  https://github.com/lensterxyz/lenster/issues/1253#issue-1456434539

**Comment by bigint** [comment]
Then this might be a tailwind issue, closing this for now, I'll work on this later 🙇🏼

**Pull request closed without merging**
