### PR TITLE
feat: Add darkmode support for hero section

### PR DESCRIPTION
**Pull request by andriishupta**
- fix mixpanel startup issue
- add .idea folder to .gitignore

## Screenshots
image

image

### CODE REVIEW

**Comment by andriishupta** [comment]
@bigint additionally added a fix for error in `mixpanel` during start - assume I don't have required env variables, so copied `if (enabled)`.

and `.idea` to .gitignore - this is Intellij IDEA folder, but it is not like .vscode, it contains data only related to me and it is always ignored, even by some scaffolds by default

**Comment by andriishupta** [comment]
I forgot to mention in the description: Fixes #375

**Review by bigint — APPROVED** [review]
**LGTM** :shipit: 

Rad LGTM

**Comment by bigint** [comment]
Hey fren, you are now eligible for Gitpoap for contributing to Lenster 🌸, go and claim your beautiful POAP 🏃🏼‍♂️ 

https://www.gitpoap.io/gh/lensterxyz/lenster

**Comment by andriishupta** [comment]
cool, thanks!

**Pull request merged**
