### PR TITLE
fix: copy text of post, prevent jump to the detail page of the …

### LINKED ISSUE #1294: Copy text of post, But jump to the detail page of the post.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just want to copy the text, but it will go to the details page of the post.
image

### Expected Behavior

Select the text, Ctrl-C copy the text.

### Steps To Reproduce

_No response_

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by metadiver**
## What does this PR do?

Fixes #1294 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How should this be tested?

User should not be redirected to the posts/id page while making a text selection.

### CODE REVIEW

**Comment by harish-sethuraman** [comment]
Can you add a screen record of the issue? its not reproducible for me?

**Comment by bigint** [comment]
@harish-sethuraman this is happening while selecting the text

https://user-images.githubusercontent.com/69431456/206912663-b7d5e889-07e2-4358-a9bc-efe2858d8780.mov

**Review by harish-sethuraman — APPROVED** [review]
LGTM ✅

**Review by bigint — APPROVED** [review]
**LGTM** :shipit: 

Rad LGTM

**Pull request merged**
