### PR TITLE
fix settings icon padding

### LINKED ISSUE #3583: Settings icon don't have enough space aka margin on right side
image

### PR DESCRIPTION
**Pull request by foolo**
### <samp>🤖 Generated by Copilot at a25fa3a</samp>

Increased button padding in `Notification/Settings.tsx` component. This is a UI improvement for the web app.

**Before:**
Screenshot_2023-08-22_17-07-21

**After:**
Screenshot_2023-08-22_17-31-30

## Related issues

Fixes #3583

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### <samp>🤖 Generated by Copilot at a25fa3a</samp>

*  Increased the horizontal padding of the button in `Settings.tsx` ([link](https://github.com/lensterxyz/lenster/pull/3604/files?diff=unified&w=0#diff-2fcd9c5e4fbdce066774e11f489ec960f3a65a073c6a1ea1ff2166ab3ec4028cL15-R15)) to improve UI consistency

## Emoji

🖥️📏🛠️

### CODE REVIEW

**Comment by bigint** [comment]
@foolo it should be margin 🙇🏼 there is no space RN right to the button 🙇🏼

**Comment by foolo** [comment]
> @foolo it should be margin 🙇🏼 there is no space RN right to the button 🙇🏼

@bigint Ahh, okay. I'll fix it.

**Comment by foolo** [comment]
> In desk it looks bit odd 🙈
> 
> image

Ah, I thought it looked good :) It's just like before the PR. I can change it if I know how it's supposed to look.

**Comment by foolo** [comment]
> In desk it looks bit odd 🙈
> 

@bigint Ah, now I think I understand what you mean. On desktop the cogwheel should have no margin. I updated the PR again. Sorry for lots of back and forth for this tiny PR :)

Looks like this now:
Screenshot_2023-08-22_22-11-32

**Review by bigint — APPROVED** [review]

**Pull request merged**
