### PR TITLE
fix: duplicate posts and profiles

### PR DESCRIPTION
**Pull request by hungds99**
## What does this PR do?

Fixes # ([issue  #1031](https://github.com/lensterxyz/lenster/issues/1031))
Fixes # ([issue  #1364](https://github.com/lensterxyz/lenster/issues/1364))

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- I haven't read the [contributing guide](https://github.com/lensterxyz/lenster/blob/main/CONTRIBUTING.md)
- My code doesn't follow the style guidelines of this project
- I haven't performed a self-review of my own code and corrected any misspellings
- I haven't commented my code, particularly in hard-to-understand areas
- I haven't checked if my PR needs changes to the documentation
- I haven't checked if my changes generate no new warnings
- I haven't added tests that prove my fix is effective or that my feature works
- I haven't checked if new and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by bigint — APPROVED** [review]
**LGTM** :shipit: 

Rad LGTM

Great one

**Comment by bigint** [comment]
@hungds99 drop your wallet address 🙇🏼 

Will send $50 + $20 🚀

**Comment by hungds99** [comment]
@bigint My wallet address: 0x33eb679e966d117c8b2629088c7d9c013a8247d4 (Polygon)

**Comment by bigint** [comment]
Here you go @hungds99 🤑 

https://polygonscan.com/tx/0x13274fe45fb445fb1edabd40e055242c0d9e2589cf0d586bfbc9de7d566dc150

**Pull request merged**
