### PR TITLE
Revert "Revert "Revert "Revert "revert: leafwatch""""

### PR DESCRIPTION
**Pull request by bigint**
Reverts lensterxyz/lenster#1118

### CODE REVIEW

**Comment by harish-sethuraman** [comment]
ethana revertu 🤣

**Comment by bigint** [comment]
Sed laip @harish-sethuraman 😭

**Comment by sasicodes** [comment]
mental panda

**Comment by harish-sethuraman** [comment]
successfully reverted a revert PR that reverted a revert to revert leafwatch changes

**Pull request merged**
