### PR TITLE
fix paragraph spacing

### LINKED ISSUE #1193: Line break not working as expected
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

its posting like this: image

### Expected Behavior

when i input this: 
image

### Steps To Reproduce

_No response_

### What platform(s) does this occur on?

Web

### What browser(s) does this occur on?

Edge

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by foolo**
## What does this PR do?

Fixes #1193
Problem: In editor, user could not see the difference between paragraph and newline. But in the published post, paragraph and newline are displayed differently (correctly).

So in this PR, the rendering of the published post is **not** changed. Instead, we fix the style in the editor, so that user sees how the post will actually look when published.

Note: Tailwind was setting all margins to 0, so therefor all elements, both `<p>` and `<br>`  had a margin of 0.

## Appearance before PR
Screenshot_2023-01-15_09-03-29 (copy 1)

## Appearance after PR
Screenshot_2023-01-15_09-44-33 (copy 1)

## Appearance of published post (not changed with this PR)
Screenshot_2023-01-15_09-54-44

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How should this be tested?

Open editor,
Type a line
Create new paragraph by pressing Enter
Observe large spacing
Type two more lines, separated by Shift+Enter
Observe smaller spacing

### CODE REVIEW

**Comment by bigint** [comment]
@foolo IMO this should be fixed in interweave side, the composer has expected behaviour

**Comment by bigint** [comment]
Close T-3674

**Comment by foolo** [comment]
> the composer has expected behaviour

Are you sure? :) Shouldn't the editor show whether the user typed a paragraph or a newline?
(Or maybe Interweve shouldn't show any difference either? In that case it would make sense, then we simply don't support paragraphs.)

**Comment by bigint** [comment]
Yes, we have both line break (\n) and paragraph break (\n\n), this is bug in interweave, even with single \n interweave do \n\n

**Comment by foolo** [comment]
> Yes, we have both line break (\n) and paragraph break (\n\n), this is bug in interweave, even with single \n interweave do \n\n

Actually, Interweave will show **one** line break '\n', if you do a newline in editor, (Shift+Enter), and **two** line breaks ('\n\n') if you do a paragraph in editor. I have investigated it quite thorougly, I would say :)

**Comment by foolo** [comment]
Note from chat discussion: Editor needs to be modified too, so that it can only output one kind of newline (at the moment it can output either `\n` (Shift+Enter) or `\n\n` (Enter) , which means that in the output, there is no way of knowing how many newlines the editor actually showed).

**Pull request closed without merging**
